# Generated by Django 5.2.12 on 2026-05-22 08:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perintah', '0014_ttdsptspd'),
        ('spd', '0009_alter_standardrepresentasi_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisSPJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_spj', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Jenis SPJ',
                'verbose_name_plural': 'Jenis SPJ',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Penginapan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama_hotel', models.CharField(max_length=200)),
                ('alamat_hotel', models.TextField(blank=True, default='')),
                ('lama_menginap', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('harga_per_malam', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('bukti', models.FileField(blank=True, null=True, upload_to='spj/penginapan/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg'], message='Bukti dukung hanya boleh berupa PDF atau JPEG.')])),
                ('pelaksana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='perintah.pelaksana')),
                ('spt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='perintah.spt')),
            ],
            options={
                'verbose_name': 'SPJ Penginapan',
                'verbose_name_plural': 'SPJ Penginapan',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Pesawat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('harga_tiket', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('bukti', models.FileField(blank=True, null=True, upload_to='spj/pesawat/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg'], message='Bukti dukung hanya boleh berupa PDF atau JPEG.')])),
                ('jenis_spj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesawat_items', to='spj.jenisspj')),
                ('lokasi_bandara', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spj_pesawat_lokasi_bandara', to='spd.lokasi')),
                ('pelaksana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='perintah.pelaksana')),
                ('spt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='perintah.spt')),
                ('tujuan_bandara', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spj_pesawat_tujuan_bandara', to='spd.lokasi')),
            ],
            options={
                'verbose_name': 'SPJ Pesawat',
                'verbose_name_plural': 'SPJ Pesawat',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biaya', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('bukti', models.FileField(blank=True, null=True, upload_to='spj/transport/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg'], message='Bukti dukung hanya boleh berupa PDF atau JPEG.')])),
                ('jenis_spj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_items', to='spj.jenisspj')),
                ('jenis_transportasi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spj_transport', to='spd.jenistransportasi')),
                ('lokasi_berangkat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spj_transport_lokasi_berangkat', to='spd.lokasi')),
                ('pelaksana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='perintah.pelaksana')),
                ('spt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='perintah.spt')),
                ('tujuan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spj_transport_tujuan', to='spd.lokasi')),
            ],
            options={
                'verbose_name': 'SPJ Transport',
                'verbose_name_plural': 'SPJ Transport',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UangHarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uang_harian_per_hari', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_uang_harian', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('pelaksana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='perintah.pelaksana')),
                ('spt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='perintah.spt')),
            ],
            options={
                'verbose_name': 'SPJ Uang Harian',
                'verbose_name_plural': 'SPJ Uang Harian',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UangRepresentasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biaya', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('pelaksana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='perintah.pelaksana')),
                ('spt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='perintah.spt')),
            ],
            options={
                'verbose_name': 'SPJ Uang Representasi',
                'verbose_name_plural': 'SPJ Uang Representasi',
                'ordering': ['-id'],
            },
        ),
    ]
