# Generated by Django 5.2.12 on 2026-05-25 13:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perintah', '0014_ttdsptspd'),
        ('spj', '0002_seed_spj_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='penginapan',
            name='foto_hotel',
            field=models.ImageField(blank=True, null=True, upload_to='spj/penginapan/hotel/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Foto hanya boleh berupa JPG, PNG, atau WEBP.')]),
        ),
        migrations.AddField(
            model_name='penginapan',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))], verbose_name='Latitude Hotel'),
        ),
        migrations.AddField(
            model_name='penginapan',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))], verbose_name='Longitude Hotel'),
        ),
        migrations.AddField(
            model_name='penginapan',
            name='nomor_kamar',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='penginapan',
            name='tanggal_checkin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penginapan',
            name='tanggal_checkout',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penginapan',
            name='tipe_kamar',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='penginapan',
            name='verif_catatan',
            field=models.TextField(blank=True, default='', verbose_name='Catatan Verifikasi'),
        ),
        migrations.AddField(
            model_name='penginapan',
            name='verif_status',
            field=models.CharField(choices=[('draft', 'Belum Diverifikasi'), ('verified', 'Diverifikasi'), ('rejected', 'Ditolak')], default='draft', max_length=20, verbose_name='Status Verifikasi'),
        ),
        migrations.AddField(
            model_name='penginapan',
            name='verified_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='penginapan',
            name='verified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_verified_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pesawat',
            name='kode_booking',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pesawat',
            name='nama_maskapai',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pesawat',
            name='nomor_tiket',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pesawat',
            name='tanggal_penerbangan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesawat',
            name='verif_catatan',
            field=models.TextField(blank=True, default='', verbose_name='Catatan Verifikasi'),
        ),
        migrations.AddField(
            model_name='pesawat',
            name='verif_status',
            field=models.CharField(choices=[('draft', 'Belum Diverifikasi'), ('verified', 'Diverifikasi'), ('rejected', 'Ditolak')], default='draft', max_length=20, verbose_name='Status Verifikasi'),
        ),
        migrations.AddField(
            model_name='pesawat',
            name='verified_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='pesawat',
            name='verified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_verified_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transport',
            name='verif_catatan',
            field=models.TextField(blank=True, default='', verbose_name='Catatan Verifikasi'),
        ),
        migrations.AddField(
            model_name='transport',
            name='verif_status',
            field=models.CharField(choices=[('draft', 'Belum Diverifikasi'), ('verified', 'Diverifikasi'), ('rejected', 'Ditolak')], default='draft', max_length=20, verbose_name='Status Verifikasi'),
        ),
        migrations.AddField(
            model_name='transport',
            name='verified_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='verified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_verified_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uangharian',
            name='verif_catatan',
            field=models.TextField(blank=True, default='', verbose_name='Catatan Verifikasi'),
        ),
        migrations.AddField(
            model_name='uangharian',
            name='verif_status',
            field=models.CharField(choices=[('draft', 'Belum Diverifikasi'), ('verified', 'Diverifikasi'), ('rejected', 'Ditolak')], default='draft', max_length=20, verbose_name='Status Verifikasi'),
        ),
        migrations.AddField(
            model_name='uangharian',
            name='verified_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='uangharian',
            name='verified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_verified_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uangrepresentasi',
            name='verif_catatan',
            field=models.TextField(blank=True, default='', verbose_name='Catatan Verifikasi'),
        ),
        migrations.AddField(
            model_name='uangrepresentasi',
            name='verif_status',
            field=models.CharField(choices=[('draft', 'Belum Diverifikasi'), ('verified', 'Diverifikasi'), ('rejected', 'Ditolak')], default='draft', max_length=20, verbose_name='Status Verifikasi'),
        ),
        migrations.AddField(
            model_name='uangrepresentasi',
            name='verified_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='uangrepresentasi',
            name='verified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_verified_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LaporanPerjalanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verif_status', models.CharField(choices=[('draft', 'Belum Diverifikasi'), ('verified', 'Diverifikasi'), ('rejected', 'Ditolak')], default='draft', max_length=20, verbose_name='Status Verifikasi')),
                ('verif_catatan', models.TextField(blank=True, default='', verbose_name='Catatan Verifikasi')),
                ('verified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('judul', models.CharField(max_length=250)),
                ('dasar_pelaksanaan', models.TextField(blank=True, default='')),
                ('maksud_perjalanan', models.TextField(blank=True, default='')),
                ('instansi_dikunjungi', models.TextField(blank=True, default='')),
                ('waktu_pelaksanaan', models.TextField(blank=True, default='')),
                ('hasil', models.TextField()),
                ('penutup', models.TextField(blank=True, default='Demikian Laporan Perjalanan Dinas ini dibuat, sebagai bahan Laporan.')),
                ('foto_1', models.ImageField(upload_to='spj/laporan/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Foto hanya boleh berupa JPG, PNG, atau WEBP.')])),
                ('foto_2', models.ImageField(blank=True, null=True, upload_to='spj/laporan/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Foto hanya boleh berupa JPG, PNG, atau WEBP.')])),
                ('foto_3', models.ImageField(blank=True, null=True, upload_to='spj/laporan/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Foto hanya boleh berupa JPG, PNG, atau WEBP.')])),
                ('foto_4', models.ImageField(blank=True, null=True, upload_to='spj/laporan/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Foto hanya boleh berupa JPG, PNG, atau WEBP.')])),
                ('pelaksana', models.ForeignKey(help_text='Pelaksana yang menginput laporan. Cukup satu laporan untuk satu SPT.', on_delete=django.db.models.deletion.PROTECT, related_name='laporan_perjalanan', to='perintah.pelaksana')),
                ('spt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laporan_perjalanan', to='perintah.spt')),
                ('verified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_verified_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Laporan Perjalanan Dinas',
                'verbose_name_plural': 'Laporan Perjalanan Dinas',
                'ordering': ['-id'],
            },
        ),
    ]
