# Generated by Django 5.2.12 on 2026-06-02 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spd', '0010_bandara'),
        ('spj', '0003_penginapan_foto_hotel_penginapan_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesawat',
            name='lokasi_bandara',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spj_pesawat_lokasi_bandara', to='spd.bandara'),
        ),
        migrations.AlterField(
            model_name='pesawat',
            name='tujuan_bandara',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spj_pesawat_tujuan_bandara', to='spd.bandara'),
        ),
    ]
