# Generated by Django 5.2.12 on 2026-05-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spj', '0003_penginapan_foto_hotel_penginapan_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporanperjalanan',
            name='penutup',
            field=models.TextField(blank=True, default='Demikian Laporan Perjalanan Dinas ini dibuat, sebagai bahan Laporan.'),
        ),
    ]
