# Generated by Django 5.2.12 on 2026-06-02 04:40

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perintah', '0014_ttdsptspd'),
        ('spd', '0010_bandara'),
        ('spj', '0004_alter_pesawat_lokasi_bandara_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laporanperjalanan',
            name='verif_catatan',
        ),
        migrations.RemoveField(
            model_name='penginapan',
            name='verif_catatan',
        ),
        migrations.RemoveField(
            model_name='pesawat',
            name='verif_catatan',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='verif_catatan',
        ),
        migrations.RemoveField(
            model_name='uangharian',
            name='verif_catatan',
        ),
        migrations.RemoveField(
            model_name='uangrepresentasi',
            name='verif_catatan',
        ),
        migrations.AddField(
            model_name='laporanperjalanan',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))], verbose_name='Latitude Lokasi Foto'),
        ),
        migrations.AddField(
            model_name='laporanperjalanan',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))], verbose_name='Longitude Lokasi Foto'),
        ),
        migrations.AlterField(
            model_name='penginapan',
            name='bukti',
            field=models.FileField(blank=True, null=True, upload_to='spj/penginapan/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp'], message='Bukti dukung hanya boleh berupa PDF atau foto.')]),
        ),
        migrations.AlterField(
            model_name='pesawat',
            name='bukti',
            field=models.FileField(blank=True, null=True, upload_to='spj/pesawat/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp'], message='Bukti dukung hanya boleh berupa PDF atau foto.')]),
        ),
        migrations.AlterField(
            model_name='transport',
            name='bukti',
            field=models.FileField(blank=True, null=True, upload_to='spj/transport/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp'], message='Bukti dukung hanya boleh berupa PDF atau foto.')]),
        ),
        migrations.AddConstraint(
            model_name='penginapan',
            constraint=models.UniqueConstraint(fields=('spt', 'pelaksana'), name='unique_spj_penginapan_spt_pelaksana'),
        ),
        migrations.AddConstraint(
            model_name='pesawat',
            constraint=models.UniqueConstraint(fields=('spt', 'pelaksana', 'jenis_spj'), name='unique_spj_pesawat_spt_pelaksana_jenis'),
        ),
        migrations.AddConstraint(
            model_name='transport',
            constraint=models.UniqueConstraint(fields=('spt', 'pelaksana', 'jenis_spj', 'jenis_transportasi'), name='unique_spj_transport_spt_pelaksana_jenis_transport'),
        ),
        migrations.AddConstraint(
            model_name='uangharian',
            constraint=models.UniqueConstraint(fields=('spt', 'pelaksana'), name='unique_spj_uang_harian_spt_pelaksana'),
        ),
        migrations.AddConstraint(
            model_name='uangrepresentasi',
            constraint=models.UniqueConstraint(fields=('spt', 'pelaksana'), name='unique_spj_representasi_spt_pelaksana'),
        ),
    ]
