# Generated by Django 5.2.12 on 2026-06-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spj', '0005_remove_laporanperjalanan_verif_catatan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporanperjalanan',
            name='isi_pertemuan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='laporanperjalanan',
            name='pembukaan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='laporanperjalanan',
            name='hasil',
            field=models.TextField(blank=True, default=''),
        ),
    ]
