# Generated by Django 5.2.12 on 2026-06-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spj', '0006_laporanperjalanan_isi_pertemuan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='tanggal_berangkat',
            field=models.DateField(blank=True, null=True),
        ),
    ]
