services:

  web:
    build: .

    container_name: perjadin_apps
    expose:
      - "80"
    
    ports:
      - "8085:80"

    restart: always

    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media

    secrets:
      - db_name
      - db_user
      - db_password
      - secret_key

    environment:
      DB_HOST: postgres
      DB_PORT: 5432

      DEBUG: "False"

      USE_HTTPS: "False"
      SECURE_SSL_REDIRECT: "False"

      ALLOWED_HOSTS: "103.188.249.54,perjadin.bkadasahan.ddns.net,192.168.66.5,192.168.66.167,127.0.0.1,localhost"

    networks:
      - production_network

networks:
  production_network:
    external: true

secrets:
  db_name:
    file: ./secrets/db_name.txt

  db_user:
    file: ./secrets/db_user.txt

  db_password:
    file: ./secrets/db_password.txt

  secret_key:
    file: ./secrets/secret_key.txt