# Generated by Django 5.2.12 on 2026-04-09 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisJabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Pangkat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pangkat', models.CharField(max_length=100)),
                ('golongan', models.CharField(max_length=10)),
                ('ruang', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['golongan', 'ruang'],
            },
        ),
        migrations.CreateModel(
            name='StatusASN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Penandatangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('nip', models.CharField(max_length=30)),
                ('tugas', models.CharField(max_length=200)),
                ('jenis_jabatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penandatangan', to='umum.jenisjabatan')),
                ('opd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penandatangan', to='profiles.opd')),
                ('pangkat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penandatangan', to='umum.pangkat')),
            ],
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=30, unique=True)),
                ('nama', models.CharField(max_length=200)),
                ('jabatan', models.CharField(max_length=200)),
                ('tgl_lahir', models.DateField(blank=True, null=True)),
                ('jenis_jabatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pegawai', to='umum.jenisjabatan')),
                ('opd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pegawai', to='profiles.opd')),
                ('pangkat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pegawai', to='umum.pangkat')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pegawai', to='umum.statusasn')),
            ],
        ),
    ]
