# Generated by Django 5.2.12 on 2026-04-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penandatangan',
            name='nip',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
