# Generated by Django 5.2.12 on 2026-04-11 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umum', '0002_alter_penandatangan_nip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pegawai',
            options={'ordering': ['id']},
        ),
    ]
