# Generated by Django 5.2.12 on 2026-04-11 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umum', '0003_alter_pegawai_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penandatangan',
            options={'ordering': ['id']},
        ),
    ]
