# Generated by Django 5.2.12 on 2026-04-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umum', '0004_alter_penandatangan_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenisjabatan',
            name='nama',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='pangkat',
            name='pangkat',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='statusasn',
            name='nama',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
