# Generated by Codex on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umum', '0005_alter_jenisjabatan_nama_alter_pangkat_pangkat_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='penandatangan',
            constraint=models.UniqueConstraint(
                fields=('nama', 'jenis_jabatan'),
                name='uniq_penandatangan_nama_jenis_jabatan',
            ),
        ),
    ]
