# Generated by Django 5.2.12 on 2026-04-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umum', '0006_penandatangan_unique_nama_jenis_jabatan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tingkat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tingkat', models.CharField(max_length=100, unique=True)),
                ('ket', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
