# Generated by Django 5.2.12 on 2026-04-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umum', '0007_tingkat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tingkat',
            name='ket',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
