# Generated by Django 5.2.12 on 2026-04-22 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umum', '0008_alter_tingkat_ket'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawai',
            name='tingkat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pegawai', to='umum.tingkat'),
        ),
    ]
