# Generated by Django 5.2.12 on 2026-04-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umum', '0009_pegawai_tingkat'),
    ]

    operations = [
        migrations.AddField(
            model_name='tingkat',
            name='kapal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tingkat',
            name='keteraapian',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tingkat',
            name='lainnya',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tingkat',
            name='pesawat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
