# Generated by Django 5.2.12 on 2026-04-24 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umum', '0010_tingkat_kapal_tingkat_keteraapian_tingkat_lainnya_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tingkat',
            old_name='keteraapian',
            new_name='keretaapian',
        ),
    ]
