# Generated by Django 5.2.12 on 2026-04-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umum', '0011_rename_keteraapian_tingkat_keretaapian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pangkat',
            name='pangkat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pangkat',
            name='ruang',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='pangkat',
            constraint=models.UniqueConstraint(fields=('pangkat', 'golongan', 'ruang'), name='unique_pangkat_golongan_ruang'),
        ),
    ]
