# Generated by Django 5.2.12 on 2026-04-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umum', '0012_alter_pangkat_pangkat_alter_pangkat_ruang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenisjabatan',
            name='fungsi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jenisjabatan',
            name='keterangan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
