# Generated by Django 5.2.12 on 2026-04-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umum', '0013_jenisjabatan_fungsi_jenisjabatan_keterangan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eselon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eselon', models.CharField(max_length=100, unique=True)),
                ('keterangan', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
