# Generated by Django 5.2.12 on 2026-04-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('umum', '0015_pegawai_eselon'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pegawai',
            constraint=models.UniqueConstraint(fields=('nip', 'eselon', 'jenis_jabatan'), name='unique_pegawai_nip_eselon_jenis_jabatan'),
        ),
    ]
