# Generated by Django 5.2.12 on 2026-04-27 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('umum', '0016_pegawai_unique_pegawai_nip_eselon_jenis_jabatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawai',
            name='eselon',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pegawai', to='umum.eselon'),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='jenis_jabatan',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pegawai', to='umum.jenisjabatan'),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='opd',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pegawai', to='profiles.opd'),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='pangkat',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pegawai', to='umum.pangkat'),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='status',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pegawai', to='umum.statusasn'),
        ),
    ]
