# Generated by Django 5.2.12 on 2026-04-27 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umum', '0018_alter_pegawai_eselon_alter_pegawai_jenis_jabatan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawai',
            name='eselon',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pegawai', to='umum.eselon'),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='jenis_jabatan',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pegawai', to='umum.jenisjabatan'),
        ),
    ]
