# Generated by Django 5.2.12 on 2026-04-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umum', '0019_alter_pegawai_eselon_alter_pegawai_jenis_jabatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawai',
            name='nip',
            field=models.CharField(max_length=30),
        ),
    ]
