# Generated by Django 5.2.12 on 2026-04-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umum', '0020_alter_pegawai_nip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pemda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pemda', models.CharField(max_length=200, unique=True)),
                ('nama_dinas', models.CharField(max_length=200, unique=True)),
                ('alamat', models.CharField(blank=True, max_length=300, null=True)),
                ('telepon', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pemda_logos/')),
                ('jenis_kop', models.CharField(blank=True, choices=[('1', 'Kepala Daerah'), ('2', 'Wakil Kepala Daerah'), ('3', 'Dinas/Badan/Kantor')], max_length=100, null=True)),
            ],
            options={
                'ordering': ['nama_pemda'],
            },
        ),
    ]
