# Generated by Django 5.2.12 on 2026-04-30 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("umum", "0021_pemda"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pemda",
            options={
                "ordering": ["nama_pemda"],
                "verbose_name": "Pemda",
                "verbose_name_plural": "Pemda",
            },
        ),
    ]
