# Generated by Django 5.2.12 on 2026-04-30 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('umum', '0022_alter_pemda_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pemda',
            name='jenis_kop',
        ),
        migrations.AddField(
            model_name='pemda',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pemda',
            name='nama_dinas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.opd', unique=True),
        ),
        migrations.AlterField(
            model_name='pemda',
            name='nama_pemda',
            field=models.CharField(max_length=200),
        ),
    ]
