# Generated by Django 5.2.12 on 2026-04-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umum', '0023_remove_pemda_jenis_kop_pemda_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemda',
            name='ibukota',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
