# Generated by Django 5.2.12 on 2026-04-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umum', '0024_pemda_ibukota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penandatangan',
            name='tugas',
            field=models.CharField(blank=True, choices=[('Bupati', 'Bupati'), ('Wakil Bupati', 'Wakil Bupati'), ('Sekretaris Daerah', 'Sekretaris Daerah'), ('Kepala', 'Kepala'), ('Kepala Bidang', 'Kepala Bidang'), ('PPK', 'Pejabat Pembuat Komitmen')], max_length=200, null=True),
        ),
    ]
