# Generated by Django 5.2.12 on 2026-04-30 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('umum', '0025_alter_penandatangan_tugas'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='penandatangan',
            name='uniq_penandatangan_nama_jenis_jabatan',
        ),
        migrations.AlterField(
            model_name='pemda',
            name='nama_dinas',
            field=models.ForeignKey(error_messages={'unique': 'Nama Dinas sudah digunakan. Pilih nama dinas lain.'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pemda', to='profiles.opd', unique=True),
        ),
        migrations.AlterField(
            model_name='penandatangan',
            name='tugas',
            field=models.CharField(choices=[('Bupati', 'Bupati'), ('Wakil Bupati', 'Wakil Bupati'), ('Sekretaris Daerah', 'Sekretaris Daerah'), ('Kepala', 'Kepala'), ('Kepala Bidang', 'Kepala Bidang'), ('PPK', 'Pejabat Pembuat Komitmen')], default='', max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='penandatangan',
            constraint=models.UniqueConstraint(fields=('nama', 'tugas', 'jenis_jabatan', 'opd'), name='uniq_penandatangan_nama_tugas_jenis_jabatan_opd', violation_error_message='Penandatangan dengan nama, tugas, jenis jabatan, dan OPD yang sama sudah ada.'),
        ),
    ]
