# Generated by Django 5.2.12 on 2026-04-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('umum', '0026_remove_penandatangan_uniq_penandatangan_nama_jenis_jabatan_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='penandatangan',
            name='uniq_penandatangan_nama_tugas_jenis_jabatan_opd',
        ),
        migrations.AddConstraint(
            model_name='penandatangan',
            constraint=models.UniqueConstraint(fields=('nip', 'nama', 'tugas', 'jenis_jabatan', 'opd'), name='uniq_penandatangan_nip_nama_tugas_jenis_jabatan_opd', violation_error_message='Penandatangan dengan NIP, nama, tugas, jenis jabatan, dan OPD yang sama sudah ada.'),
        ),
    ]
