# Generated by Django 5.2.12 on 2026-04-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('umum', '0027_remove_penandatangan_uniq_penandatangan_nama_tugas_jenis_jabatan_opd_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='penandatangan',
            name='uniq_penandatangan_nip_nama_tugas_jenis_jabatan_opd',
        ),
        migrations.AddConstraint(
            model_name='penandatangan',
            constraint=models.UniqueConstraint(fields=('nama', 'tugas', 'jenis_jabatan'), name='uniq_penandatangan_nama_tugas_jenis_jabatan', violation_error_message='Penandatangan dengan Nama, tugas, dan jenis jabatan yang sama sudah ada.'),
        ),
    ]
