# Generated by Django 5.2.12 on 2026-04-30 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('umum', '0029_remove_penandatangan_uniq_penandatangan_nama_tugas_jenis_jabatan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemda',
            name='nama_dinas',
            field=models.OneToOneField(error_messages={'unique': 'Nama Dinas sudah digunakan. Pilih nama dinas lain.'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pemda', to='profiles.opd'),
        ),
    ]
