# Generated by Django 5.2.12 on 2026-05-01 14:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def create_default_kop_surat(apps, schema_editor):
    Pemda = apps.get_model('umum', 'Pemda')
    KopSurat = apps.get_model('umum', 'KopSurat')
    Menu = apps.get_model('menus', 'Menu')
    SubMenu = apps.get_model('menus', 'SubMenu')
    RolePermission = apps.get_model('menus', 'RolePermission')

    for pemda in Pemda.objects.all().iterator():
        KopSurat.objects.get_or_create(pemda=pemda)

    menu = Menu.objects.filter(nama__iexact='Umum').order_by('id').first()
    if menu is None:
        menu = Menu.objects.create(
            nama='Umum',
            icon='ti-settings',
            urutan=2,
        )

    submenu = SubMenu.objects.filter(url='kop_surat_list').order_by('id').first()
    if submenu is None:
        submenu = SubMenu.objects.create(
            menu=menu,
            nama='Kop Surat',
            url='kop_surat_list',
            urutan=8,
        )

    pemda_submenus = SubMenu.objects.filter(url='pemda_list')
    pemda_permissions = RolePermission.objects.filter(
        submenu__in=pemda_submenus,
    ).select_related('role')

    for permission in pemda_permissions:
        RolePermission.objects.get_or_create(
            role=permission.role,
            submenu=submenu,
            defaults={
                'can_view': permission.can_view,
                'can_add': permission.can_add,
                'can_edit': permission.can_edit,
                'can_delete': permission.can_delete,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
        ('umum', '0030_alter_pemda_nama_dinas'),
    ]

    operations = [
        migrations.CreateModel(
            name='KopSurat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_family', models.CharField(choices=[('Arial, sans-serif', 'Arial'), ('"Times New Roman", Times, serif', 'Times New Roman'), ('Calibri, Arial, sans-serif', 'Calibri'), ('Cambria, Georgia, serif', 'Cambria'), ('Garamond, "Times New Roman", serif', 'Garamond'), ('Tahoma, Geneva, sans-serif', 'Tahoma'), ('Verdana, Geneva, sans-serif', 'Verdana')], default='Arial, sans-serif', max_length=120, verbose_name='Jenis Font')),
                ('region_font_size_pt', models.PositiveSmallIntegerField(default=14, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(32)], verbose_name='Ukuran Font Nama Pemda (pt)')),
                ('office_font_size_pt', models.PositiveSmallIntegerField(default=18, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(36)], verbose_name='Ukuran Font Nama Dinas/Jabatan (pt)')),
                ('address_font_size_pt', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(20)], verbose_name='Ukuran Font Alamat (pt)')),
                ('contact_font_size_pt', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(20)], verbose_name='Ukuran Font Kontak (pt)')),
                ('logo_width_px', models.PositiveSmallIntegerField(default=90, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(180)], verbose_name='Lebar Logo (px)')),
                ('logo_height_px', models.PositiveSmallIntegerField(default=90, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(180)], verbose_name='Tinggi Logo (px)')),
                ('print_scale_percent', models.PositiveSmallIntegerField(default=96, validators=[django.core.validators.MinValueValidator(75), django.core.validators.MaxValueValidator(120)], verbose_name='Skala Cetak Default (%)')),
                ('pemda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kop_surat', to='umum.pemda')),
            ],
            options={
                'verbose_name': 'Kop Surat',
                'verbose_name_plural': 'Kop Surat',
                'ordering': ['pemda__nama_pemda'],
            },
        ),
        migrations.RunPython(
            create_default_kop_surat,
            migrations.RunPython.noop,
        ),
    ]
