# Generated by Django 5.2.12 on 2026-05-01 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umum', '0031_kopsurat'),
    ]

    operations = [
        migrations.AddField(
            model_name='kopsurat',
            name='default_spd_number_format',
            field=models.CharField(blank=True, default='800.1.11.1/{nomor_urut}/SPD/{bulan}/{tahun}', help_text='Gunakan {nomor_urut}, {bulan}, {tahun} sebagai placeholder', max_length=100, verbose_name='Format Default Nomor SPD'),
        ),
        migrations.AddField(
            model_name='kopsurat',
            name='default_spt_number_format',
            field=models.CharField(blank=True, default='800.1.11.1/{nomor_urut}/{bulan}/{tahun}', help_text='Gunakan {nomor_urut}, {bulan}, {tahun} sebagai placeholder', max_length=100, verbose_name='Format Default Nomor SPT'),
        ),
        migrations.AddField(
            model_name='kopsurat',
            name='footer_alignment',
            field=models.CharField(choices=[('left', 'Kiri'), ('center', 'Tengah'), ('right', 'Kanan')], default='center', max_length=10, verbose_name='Posisi Footer'),
        ),
        migrations.AddField(
            model_name='kopsurat',
            name='footer_font_size_pt',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(20)], verbose_name='Ukuran Font Footer (pt)'),
        ),
        migrations.AddField(
            model_name='kopsurat',
            name='footer_text',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Teks Footer'),
        ),
        migrations.AddField(
            model_name='kopsurat',
            name='header_alignment',
            field=models.CharField(choices=[('left', 'Kiri'), ('center', 'Tengah'), ('right', 'Kanan')], default='center', max_length=10, verbose_name='Posisi Header'),
        ),
        migrations.AddField(
            model_name='kopsurat',
            name='header_font_size_pt',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(20)], verbose_name='Ukuran Font Header (pt)'),
        ),
        migrations.AddField(
            model_name='kopsurat',
            name='header_text',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Teks Header'),
        ),
        migrations.AddField(
            model_name='kopsurat',
            name='margin_bottom_mm',
            field=models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)], verbose_name='Margin Bawah (mm)'),
        ),
        migrations.AddField(
            model_name='kopsurat',
            name='margin_left_mm',
            field=models.PositiveSmallIntegerField(default=18, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)], verbose_name='Margin Kiri (mm)'),
        ),
        migrations.AddField(
            model_name='kopsurat',
            name='margin_right_mm',
            field=models.PositiveSmallIntegerField(default=18, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)], verbose_name='Margin Kanan (mm)'),
        ),
        migrations.AddField(
            model_name='kopsurat',
            name='margin_top_mm',
            field=models.PositiveSmallIntegerField(default=18, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)], verbose_name='Margin Atas (mm)'),
        ),
    ]
