# Generated by Django 5.2.12 on 2026-05-03 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umum', '0032_kopsurat_default_spd_number_format_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kopsurat',
            name='footer_alignment',
        ),
        migrations.RemoveField(
            model_name='kopsurat',
            name='footer_font_size_pt',
        ),
        migrations.RemoveField(
            model_name='kopsurat',
            name='footer_text',
        ),
        migrations.RemoveField(
            model_name='kopsurat',
            name='header_alignment',
        ),
        migrations.RemoveField(
            model_name='kopsurat',
            name='header_font_size_pt',
        ),
        migrations.RemoveField(
            model_name='kopsurat',
            name='header_text',
        ),
        migrations.AlterField(
            model_name='kopsurat',
            name='margin_bottom_mm',
            field=models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Margin Bawah (mm)'),
        ),
        migrations.AlterField(
            model_name='kopsurat',
            name='margin_left_mm',
            field=models.PositiveSmallIntegerField(default=18, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Margin Kiri (mm)'),
        ),
        migrations.AlterField(
            model_name='kopsurat',
            name='margin_right_mm',
            field=models.PositiveSmallIntegerField(default=18, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Margin Kanan (mm)'),
        ),
        migrations.AlterField(
            model_name='kopsurat',
            name='margin_top_mm',
            field=models.PositiveSmallIntegerField(default=18, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Margin Atas (mm)'),
        ),
    ]
