# Generated by Django 5.2.12 on 2026-05-04 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umum', '0033_remove_kopsurat_footer_alignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kopsurat',
            name='default_spt_number_format',
            field=models.CharField(blank=True, default='800.1.11.1/{nomor_urut}/BKAD/{bulan}/{tahun}', help_text='Gunakan {nomor_urut}, {bulan}, {tahun} sebagai placeholder', max_length=100, verbose_name='Format Default Nomor SPT'),
        ),
        migrations.AlterField(
            model_name='kopsurat',
            name='logo_height_px',
            field=models.PositiveSmallIntegerField(default=90, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)], verbose_name='Tinggi Logo (px)'),
        ),
        migrations.AlterField(
            model_name='kopsurat',
            name='logo_width_px',
            field=models.PositiveSmallIntegerField(default=90, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)], verbose_name='Lebar Logo (px)'),
        ),
    ]
