# Generated by Django 5.2.12 on 2026-05-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umum', '0034_alter_kopsurat_default_spt_number_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemda',
            name='password_standar',
            field=models.CharField(blank=True, default='', help_text='Password standar untuk login pegawai dengan NIP.', max_length=128),
        ),
    ]
