# Generated by Django 5.2.12 on 2026-05-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umum', '0035_pemda_password_standar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawai',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pegawai/foto/'),
        ),
    ]
