# Generated by Django 5.2.12 on 2026-06-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umum', '0036_pegawai_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kopsurat',
            name='font_family',
            field=models.CharField(choices=[('Arial, sans-serif', 'Arial'), ('"Times New Roman", Times, serif', 'Times New Roman'), ('Calibri, Arial, sans-serif', 'Calibri'), ('Cambria, Georgia, serif', 'Cambria'), ('Garamond, "Times New Roman", serif', 'Garamond'), ('Tahoma, Geneva, sans-serif', 'Tahoma'), ('Verdana, Geneva, sans-serif', 'Verdana')], default='Arial', max_length=120, verbose_name='Jenis Font'),
        ),
    ]
