# Generated by Django 5.2.12 on 2026-07-27 10:57

from django.db import migrations, models


DEFAULT_TUGAS = [
    ("Bupati", "Bupati"),
    ("Wakil Bupati", "Wakil Bupati"),
    ("Sekretaris Daerah", "Sekretaris Daerah"),
    ("Kepala", "Kepala"),
    ("Kepala Bidang", "Kepala Bidang"),
    ("PPK", "Pejabat Pembuat Komitmen"),
    ("Bendahara", "Bendahara Pengeluaran"),
]


def seed_tugas(apps, schema_editor):
    Tugas = apps.get_model("umum", "Tugas")
    for nama, keterangan in DEFAULT_TUGAS:
        Tugas.objects.update_or_create(
            nama=nama,
            defaults={"keterangan": keterangan},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('umum', '0037_alter_kopsurat_font_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, unique=True)),
                ('keterangan', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RunPython(seed_tugas, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='penandatangan',
            name='tugas',
            field=models.CharField(choices=[('Bupati', 'Bupati'), ('Wakil Bupati', 'Wakil Bupati'), ('Sekretaris Daerah', 'Sekretaris Daerah'), ('Kepala', 'Kepala'), ('Kepala Bidang', 'Kepala Bidang'), ('PPK', 'Pejabat Pembuat Komitmen'), ('Bendahara', 'Bendahara Pengeluaran')], default='', max_length=200, null=True),
        ),
    ]
