# Generated by Django 5.2.12 on 2026-07-27 11:10

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_TUGAS = [
    ("Bupati", "Bupati"),
    ("Wakil Bupati", "Wakil Bupati"),
    ("Sekretaris Daerah", "Sekretaris Daerah"),
    ("Kepala", "Kepala"),
    ("Kepala Bidang", "Kepala Bidang"),
    ("PPK", "Pejabat Pembuat Komitmen"),
    ("Bendahara", "Bendahara Pengeluaran"),
]


def convert_penandatangan_tugas_to_fk_ids(apps, schema_editor):
    Tugas = apps.get_model("umum", "Tugas")
    Penandatangan = apps.get_model("umum", "Penandatangan")

    tugas_by_name = {}
    for nama, keterangan in DEFAULT_TUGAS:
        tugas, _ = Tugas.objects.update_or_create(
            nama=nama,
            defaults={"keterangan": keterangan},
        )
        tugas_by_name[nama] = tugas

    for penandatangan in Penandatangan.objects.all():
        raw_tugas = (penandatangan.tugas or "").strip()
        if not raw_tugas:
            penandatangan.tugas = None
            penandatangan.save(update_fields=["tugas"])
            continue

        tugas = tugas_by_name.get(raw_tugas)
        if tugas is None:
            tugas, _ = Tugas.objects.get_or_create(nama=raw_tugas)
            tugas_by_name[raw_tugas] = tugas

        penandatangan.tugas = str(tugas.pk)
        penandatangan.save(update_fields=["tugas"])


class Migration(migrations.Migration):

    dependencies = [
        ('umum', '0038_tugas_alter_penandatangan_tugas'),
    ]

    operations = [
        migrations.AddField(
            model_name='penandatangan',
            name='jabatan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RunPython(
            convert_penandatangan_tugas_to_fk_ids,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='penandatangan',
            name='tugas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penandatangan', to='umum.tugas'),
        ),
    ]
