# Generated by Django 5.2.12 on 2026-09-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umum', '0039_penandatangan_jabatan_alter_penandatangan_tugas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eselon',
            options={'ordering': ['eselon', 'peringkat']},
        ),
        migrations.AddField(
            model_name='eselon',
            name='peringkat',
            field=models.CharField(default='a', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eselon',
            name='eselon',
            field=models.CharField(max_length=10),
        ),
        migrations.AddConstraint(
            model_name='eselon',
            constraint=models.UniqueConstraint(fields=('eselon', 'peringkat'), name='unique_eselon_peringkat'),
        ),
    ]
