# Generated by Django 5.2.12 on 2026-09-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umum', '0040_alter_eselon_options_eselon_peringkat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eselon',
            old_name='keterangan',
            new_name='ruang_lingkup_daerah',
        ),
        migrations.AddField(
            model_name='eselon',
            name='ruang_lingkup_pusat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
