# Generated by Django 5.2.12 on 2026-04-27 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spd', '0006_standardpenginapan_satuan'),
        ('umum', '0020_alter_pegawai_nip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_spt', models.CharField(blank=True, default='', max_length=150)),
                ('tanggal_spt', models.DateField(blank=True, null=True)),
                ('dasar', models.TextField(blank=True, null=True)),
                ('berita', models.TextField(blank=True, null=True)),
                ('lama_perjalanan', models.IntegerField(choices=[(1, '1 hari'), (2, '2 hari'), (3, '3 hari'), (4, '4 hari'), (5, '5 hari'), (6, '6 hari'), (7, '7 hari'), (8, '8 hari'), (9, '9 hari'), (10, '10 hari'), (11, '11 hari'), (12, '12 hari'), (13, '13 hari'), (14, '14 hari'), (15, '15 hari'), (16, '16 hari'), (17, '17 hari'), (18, '18 hari'), (19, '19 hari'), (20, '20 hari'), (21, '21 hari'), (22, '22 hari'), (23, '23 hari'), (24, '24 hari'), (25, '25 hari'), (26, '26 hari'), (27, '27 hari'), (28, '28 hari'), (29, '29 hari'), (30, '30 hari')])),
                ('tgl_berangkat', models.DateField()),
                ('tgl_kembali', models.DateField(blank=True, null=True)),
                ('kendaraan', models.CharField(blank=True, choices=[('transport_umum', 'Transport Umum'), ('kendaraan_dinas', 'Kenderaan Dinas')], default='', max_length=50)),
                ('jenis_kegiatan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spt_jenis_kegiatan', to='spd.jeniskegiatan')),
                ('kota_tujuan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spt_kota_tujuan', to='spd.lokasi')),
            ],
            options={
                'verbose_name': 'SPT',
                'verbose_name_plural': 'SPT',
                'ordering': ['-tanggal_spt', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Pelaksana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pelaksana', to='umum.pegawai')),
                ('spt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pelaksana', to='perintah.spt')),
            ],
            options={
                'verbose_name': 'Pelaksana',
                'verbose_name_plural': 'Pelaksana',
                'ordering': ['spt', 'nama'],
            },
        ),
    ]
