# Generated by Django 5.2.12 on 2026-04-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perintah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spt',
            name='tempat_tujuan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
