# Generated by Django 5.2.12 on 2026-04-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perintah', '0002_spt_tempat_tujuan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spt',
            name='tempat_tujuan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
