# Generated by Django 5.2.12 on 2026-04-30 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perintah', '0003_alter_spt_tempat_tujuan'),
        ('umum', '0021_pemda'),
    ]

    operations = [
        migrations.CreateModel(
            name='PemberiTugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('nip', models.CharField(max_length=30)),
                ('pangkat', models.CharField(max_length=30)),
                ('tugas', models.CharField(max_length=200)),
                ('jenis_jabatan', models.CharField(max_length=100)),
                ('opd', models.CharField(max_length=200)),
                ('penandatangan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pemberi_tugas', to='umum.penandatangan')),
                ('spt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pemberi_tugas', to='perintah.spt')),
            ],
            options={
                'verbose_name': 'Pemberi Tugas',
                'verbose_name_plural': 'Pemberi Tugas',
                'ordering': ['spt', 'penandatangan'],
            },
        ),
    ]
