# Generated by Django 5.2.12 on 2026-04-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perintah', '0004_pemberitugas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spt',
            options={'ordering': ['-id'], 'verbose_name': 'SPT', 'verbose_name_plural': 'SPT'},
        ),
        migrations.RemoveField(
            model_name='spt',
            name='nomor_spt',
        ),
        migrations.RemoveField(
            model_name='spt',
            name='tanggal_spt',
        ),
        migrations.AddField(
            model_name='pemberitugas',
            name='nomor_spt',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='pemberitugas',
            name='tanggal_spt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
