# Generated by Django 5.2.12 on 2026-04-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perintah', '0005_alter_spt_options_remove_spt_nomor_spt_and_more'),
        ('umum', '0023_remove_pemda_jenis_kop_pemda_website_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pemberitugas',
            constraint=models.UniqueConstraint(fields=('spt', 'penandatangan'), name='unique_pemberi_tugas_spt_penandatangan'),
        ),
    ]
