# Generated by Django 5.2.12 on 2026-04-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perintah', '0006_pemberitugas_unique_pemberi_tugas_spt_penandatangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemberitugas',
            name='nomor_spd',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
