# Generated by Django 5.2.12 on 2026-04-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perintah', '0007_pemberitugas_nomor_spd'),
        ('umum', '0029_remove_penandatangan_uniq_penandatangan_nama_tugas_jenis_jabatan_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pemberitugas',
            name='unique_pemberi_tugas_spt_penandatangan',
        ),
        migrations.AddConstraint(
            model_name='pemberitugas',
            constraint=models.UniqueConstraint(fields=('spt', 'penandatangan', 'nomor_spt', 'nomor_spd'), name='unique_pemberi_tugas_spt_penandatangan_nomor_spt_nomor_spd'),
        ),
    ]
