# Generated by Django 5.2.12 on 2026-04-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perintah', '0008_remove_pemberitugas_unique_pemberi_tugas_spt_penandatangan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemberitugas',
            name='nip',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='pemberitugas',
            name='pangkat',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
