# Generated by Django 5.2.12 on 2026-05-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perintah', '0009_alter_pemberitugas_nip_alter_pemberitugas_pangkat'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemberitugas',
            name='nomor_urut',
            field=models.CharField(blank=True, default='', help_text='Nomor urut untuk generate nomor SPT/SPD otomatis', max_length=50, verbose_name='Nomor Urut'),
        ),
    ]
