# Generated by Django 5.2.12 on 2026-05-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perintah', '0010_pemberitugas_nomor_urut'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pemberitugas',
            name='unique_pemberi_tugas_spt_penandatangan_nomor_spt_nomor_spd',
        ),
        migrations.AddConstraint(
            model_name='pemberitugas',
            constraint=models.UniqueConstraint(fields=('spt', 'penandatangan'), name='unique_pemberi_tugas_spt_penandatangan'),
        ),
    ]
