# Generated by Django 5.2.12 on 2026-05-21 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perintah', '0013_spt_kota_tujuan_tambahan'),
    ]

    operations = [
        migrations.CreateModel(
            name='TtdSptSpd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardcopy', models.FileField(blank=True, null=True, upload_to='hardcopy/')),
                ('pemberi_tugas', models.OneToOneField(error_messages={'unique': 'Nama Dinas sudah digunakan. Pilih nama dinas lain.'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttdsptspd', to='perintah.pemberitugas')),
            ],
            options={
                'verbose_name': 'Tanda Tangan SPT/SPD',
                'verbose_name_plural': 'Tanda Tangan SPT/SPD',
                'ordering': ['pemberi_tugas'],
            },
        ),
    ]
