# Generated by Django 5.2.12 on 2026-06-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perintah', '0014_ttdsptspd'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Nomor WhatsApp')),
                ('step', models.CharField(choices=[('DASAR_SPT', 'Input Dasar SPT'), ('BERITA_SPT', 'Input Berita SPT'), ('KOTA_TUJUAN', 'Input Kota Tujuan'), ('KOTA_TUJUAN_TAMBAHAN', 'Input Kota Tujuan Tambahan'), ('TEMPAT_TUJUAN', 'Input Tempat Tujuan'), ('INPUT_PELAKSANA', 'Input Pelaksana'), ('TAMBAH_PELAKSANA', 'Tambah Pelaksana'), ('INPUT_JENIS_KEGIATAN', 'Input Jenis Kegiatan'), ('INPUT_LAMA_PERJALANAN', 'Input Lama Perjalanan'), ('INPUT_TANGGAL', 'Input Tanggal'), ('INPUT_KENDARAAN', 'Input Kendaraan'), ('INPUT_PENANDATANGAN', 'Input Penandatangan'), ('KONFIRMASI', 'Konfirmasi'), ('SELESAI', 'Selesai')], db_index=True, default='INPUT_PELAKSANA', max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Data sementara percakapan WhatsApp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WA Session',
                'verbose_name_plural': 'WA Sessions',
                'ordering': ['-updated_at'],
            },
        ),
    ]
