# Generated by Django 5.2.12 on 2026-07-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perintah', '0015_wasession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spt',
            name='kendaraan',
            field=models.CharField(blank=True, choices=[('transport_umum', 'Transportasi Umum'), ('kendaraan_dinas', 'Kenderaan Dinas')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='wasession',
            name='step',
            field=models.CharField(choices=[('DASAR_SPT', 'Input Dasar SPT'), ('BERITA_SPT', 'Input Berita SPT'), ('KOTA_TUJUAN', 'Input Kota Tujuan'), ('PILIH_KOTA_TUJUAN', 'Pilih Kota Tujuan'), ('KOTA_TUJUAN_TAMBAHAN', 'Input Kota Tujuan Tambahan'), ('PILIH_KOTA_TUJUAN_TAMBAHAN', 'Pilih Kota Tujuan Tambahan'), ('KONFIRMASI_KOTA_TUJUAN_TAMBAHAN', 'Konfirmasi Kota Tujuan Tambahan'), ('TEMPAT_TUJUAN', 'Input Tempat Tujuan'), ('INPUT_PELAKSANA', 'Input Pelaksana'), ('PILIH_PELAKSANA', 'Pilih Pelaksana'), ('TAMBAH_PELAKSANA', 'Tambah Pelaksana'), ('INPUT_JENIS_KEGIATAN', 'Input Jenis Kegiatan'), ('PILIH_JENIS_KEGIATAN', 'Pilih Jenis Kegiatan'), ('INPUT_LAMA_PERJALANAN', 'Input Lama Perjalanan'), ('INPUT_TANGGAL', 'Input Tanggal'), ('INPUT_KENDERAAN', 'Input Kendaraan'), ('PILIH_JENIS_KENDARAAN', 'Pilih Jenis Kendaraan'), ('INPUT_PENANDATANGAN', 'Input Penandatangan'), ('PILIH_PENANDATANGAN', 'Pilih Penandatangan'), ('KONFIRMASI', 'Konfirmasi'), ('SELESAI', 'Selesai')], db_index=True, default='INPUT_PELAKSANA', max_length=50),
        ),
    ]
