# Generated by Django 5.2.12 on 2026-04-22 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('umum', '0010_tingkat_kapal_tingkat_keteraapian_tingkat_lainnya_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DasarPeraturan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_peraturan', models.CharField(max_length=255)),
                ('nomor_peraturan', models.CharField(blank=True, max_length=150, null=True)),
                ('tanggal_peraturan', models.DateField(blank=True, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dasar Peraturan',
                'verbose_name_plural': 'Dasar Peraturan',
                'ordering': ['-tanggal_peraturan', 'nama_peraturan'],
            },
        ),
        migrations.CreateModel(
            name='JenisKegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Jenis Kegiatan',
                'verbose_name_plural': 'Jenis Kegiatan',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='JenisSPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Jenis SPD',
                'verbose_name_plural': 'Jenis SPD',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='JenisTransportasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Jenis Transportasi',
                'verbose_name_plural': 'Jenis Transportasi',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Lokasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokasi', models.CharField(max_length=150, unique=True)),
                ('jenis_spd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lokasi', to='spd.jenisspd')),
            ],
            options={
                'verbose_name': 'Lokasi',
                'verbose_name_plural': 'Lokasi',
                'ordering': ['lokasi'],
            },
        ),
        migrations.CreateModel(
            name='StandardPenginapan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biaya', models.DecimalField(decimal_places=2, max_digits=14)),
                ('dasar_peraturan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='spd.dasarperaturan')),
                ('lokasi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_penginapan', to='spd.lokasi')),
                ('tingkat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_penginapan', to='umum.tingkat')),
            ],
            options={
                'verbose_name': 'Standar Penginapan',
                'verbose_name_plural': 'Standar Penginapan',
                'ordering': ['lokasi', 'tingkat'],
                'constraints': [models.UniqueConstraint(fields=('lokasi', 'tingkat', 'dasar_peraturan'), name='unique_penginapan_lokasi_tingkat_dasar_peraturan')],
            },
        ),
        migrations.CreateModel(
            name='StandardPesawat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biaya', models.DecimalField(decimal_places=2, max_digits=14)),
                ('dasar_peraturan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='spd.dasarperaturan')),
                ('kota_asal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_pesawat_asal', to='spd.lokasi')),
                ('kota_tujuan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_pesawat_tujuan', to='spd.lokasi')),
                ('tingkat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_pesawat', to='umum.tingkat')),
            ],
            options={
                'verbose_name': 'Standar Tiket Pesawat',
                'verbose_name_plural': 'Standar Tiket Pesawat',
                'ordering': ['kota_asal', 'kota_tujuan', 'tingkat'],
                'constraints': [models.UniqueConstraint(fields=('kota_asal', 'kota_tujuan', 'tingkat', 'dasar_peraturan'), name='unique_pesawat_asal_tujuan_tingkat_dasar_peraturan')],
            },
        ),
        migrations.CreateModel(
            name='StandardRepresentasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biaya', models.DecimalField(decimal_places=2, max_digits=14)),
                ('dasar_peraturan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='spd.dasarperaturan')),
                ('jenis_jabatan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_representasi', to='umum.jenisjabatan')),
                ('jenis_spd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_representasi', to='spd.jenisspd')),
            ],
            options={
                'verbose_name': 'Standar Representasi',
                'verbose_name_plural': 'Standar Representasi',
                'ordering': ['jenis_jabatan', 'jenis_spd'],
                'constraints': [models.UniqueConstraint(fields=('jenis_jabatan', 'jenis_spd', 'dasar_peraturan'), name='unique_representasi_jabatan_spd_dasar_peraturan')],
            },
        ),
        migrations.CreateModel(
            name='StandardTransportasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('satuan', models.CharField(max_length=50)),
                ('biaya', models.DecimalField(decimal_places=2, max_digits=14)),
                ('dasar_peraturan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='spd.dasarperaturan')),
                ('jenis_transportasi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_transportasi', to='spd.jenistransportasi')),
                ('kota_tujuan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_transportasi', to='spd.lokasi')),
            ],
            options={
                'verbose_name': 'Standar Transportasi',
                'verbose_name_plural': 'Standar Transportasi',
                'ordering': ['jenis_transportasi', 'kota_tujuan'],
                'constraints': [models.UniqueConstraint(fields=('jenis_transportasi', 'kota_tujuan', 'dasar_peraturan'), name='unique_transportasi_jenis_kota_dasar_peraturan')],
            },
        ),
        migrations.CreateModel(
            name='StandardUangHarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('satuan', models.CharField(max_length=50)),
                ('biaya', models.DecimalField(decimal_places=2, max_digits=14)),
                ('dasar_peraturan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='spd.dasarperaturan')),
                ('jenis_kegiatan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_uang_harian', to='spd.jeniskegiatan')),
                ('lokasi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_uang_harian', to='spd.lokasi')),
            ],
            options={
                'verbose_name': 'Standar Uang Harian',
                'verbose_name_plural': 'Standar Uang Harian',
                'ordering': ['lokasi', 'jenis_kegiatan'],
                'constraints': [models.UniqueConstraint(fields=('lokasi', 'jenis_kegiatan', 'dasar_peraturan'), name='unique_uang_harian_lokasi_kegiatan_dasar_peraturan')],
            },
        ),
    ]
