# Generated by Django 5.2.12 on 2026-04-23 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lokasi',
            options={'ordering': ['jenis_spd', 'lokasi'], 'verbose_name': 'Lokasi', 'verbose_name_plural': 'Lokasi'},
        ),
    ]
