# Generated by Django 5.2.12 on 2026-04-24 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spd', '0002_alter_lokasi_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardpenginapan',
            name='aktif',
        ),
        migrations.RemoveField(
            model_name='standardpesawat',
            name='aktif',
        ),
        migrations.RemoveField(
            model_name='standardrepresentasi',
            name='aktif',
        ),
        migrations.RemoveField(
            model_name='standardtransportasi',
            name='aktif',
        ),
        migrations.RemoveField(
            model_name='standarduangharian',
            name='aktif',
        ),
    ]
