# Generated by Django 5.2.12 on 2026-04-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spd', '0003_remove_standardpenginapan_aktif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lokasi',
            name='kota',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
