# Generated by Django 5.2.12 on 2026-04-24 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spd', '0004_lokasi_kota'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lokasi',
            options={'ordering': ['jenis_spd_id', 'lokasi'], 'verbose_name': 'Lokasi', 'verbose_name_plural': 'Lokasi'},
        ),
    ]
