# Generated by Django 5.2.12 on 2026-04-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spd', '0005_alter_lokasi_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpenginapan',
            name='satuan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
