# Generated by Django 5.2.12 on 2026-05-21 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spd', '0006_standardpenginapan_satuan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jeniskegiatan',
            options={'ordering': ['id'], 'verbose_name': 'Jenis Kegiatan', 'verbose_name_plural': 'Jenis Kegiatan'},
        ),
        migrations.AlterModelOptions(
            name='jenisspd',
            options={'ordering': ['id'], 'verbose_name': 'Jenis SPD', 'verbose_name_plural': 'Jenis SPD'},
        ),
        migrations.AlterModelOptions(
            name='jenistransportasi',
            options={'ordering': ['id'], 'verbose_name': 'Jenis Transportasi', 'verbose_name_plural': 'Jenis Transportasi'},
        ),
    ]
