# Generated by Django 5.2.12 on 2026-05-22 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spd', '0007_alter_jeniskegiatan_options_alter_jenisspd_options_and_more'),
        ('umum', '0034_alter_kopsurat_default_spt_number_format_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standardrepresentasi',
            options={'ordering': ['jenis_jabatan', 'tingkat_spd'], 'verbose_name': 'Standar Representasi', 'verbose_name_plural': 'Standar Representasi'},
        ),
        migrations.RemoveConstraint(
            model_name='standardrepresentasi',
            name='unique_representasi_jabatan_spd_dasar_peraturan',
        ),
        migrations.RemoveField(
            model_name='standardrepresentasi',
            name='jenis_spd',
        ),
        migrations.AddField(
            model_name='standardrepresentasi',
            name='tingkat_spd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='standard_representasi', to='umum.tingkat'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='standardrepresentasi',
            constraint=models.UniqueConstraint(fields=('jenis_jabatan', 'tingkat_spd', 'dasar_peraturan'), name='unique_representasi_jabatan_spd_dasar_peraturan'),
        ),
    ]
