# Generated by Django 5.2.12 on 2026-06-02 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spd', '0009_alter_standardrepresentasi_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bandara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150, unique=True)),
                ('kota', models.CharField(max_length=100)),
                ('provinsi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bandara', to='spd.lokasi')),
            ],
            options={
                'verbose_name': 'Bandara',
                'verbose_name_plural': 'Bandara',
                'ordering': ['id'],
            },
        ),
    ]
